# To use this INI file, set GOOGLEBIGQUERYODBCINI env to this path

[Driver]
# LogLevel(Optional): Follows abseil logging(https://abseil.io/docs/cpp/guides/logging#severity)
# 0 = (OFF) No messages should be logged.
# 1 = (ERROR) Denotes serious failures or errors that impact application functionality.
# 2 = (WARNING) Indicates potential problems or situations that might require attention.
# 3 = (INFO) Informational messages about normal events and progress.
LogLevel=0

# LogPath(Required): Folder where log files would be created. The folder must exist.
# Note: This is optional if `LogLevel=0`
LogPath=

# LogFileCount(Optional): Maximum number of log files created.
# Driver will start deleting the older files after this limit is reached.
LogFileCount=200

# LogFileSize(Optional): Maximum size of a log file in MB
LogFileSize=1

# MaxThreads(Optional): Maximum threads the driver will spawn for catalog APIs
MaxThreads=8
