# To use this INI file, replace <INSTALLDIR> with the
# directory the tarball was extracted to.

[ODBC]
Trace=no

[ODBC Data Sources]
BigQueryDSN=ODBC Driver for BigQuery

[BigQueryDSN]

# These values can be set here, or on the connection string.

# Description(Optional): DSN Description.
Description=ODBC Driver for BigQuery

# Driver(Required): The location where the ODBC driver is installed to.
# Driver=<INSTALLDIR>/lib/libgoogle_cloud_odbc_bq_driver.so # Linux
# Driver=<INSTALLDIR>/lib/libgoogle_cloud_odbc_bq_driver.dylib # MacOS

# Catalog(Required): The catalog to connect to. This is a required setting.
Catalog=

# SQLDialect(Optional): The SQL Dialect to use.  There are two SQL dialects:
# 0 = BigQuery Legacy SQL
# 1 = BigQuery Standard SQL (SQL 11)
# SQLDialect=1

# OAuth Mechanism(Required): The OAuth mechanism to use. There are three choices:
# 0 = Service or User Authentication
# 3 = Application Default Credentials
# 4 = External account Authentication
#
OAuthMechanism=0

# KeyFilePath(Required): For Service and External Authentication, this is a required setting.  This is the path to the stored keyfile (.p12).
# Note: This is not required for Application Default Credentials
KeyFilePath=

# TrustedCerts(Optional): Used to specify the full path of the PEM formatted file containing trusted SSL CA certificates.
# If an empty string is passed in for the configuration, the driver expects the trusted SSL CA
# certificates can be found in the file named cacerts.pem located in the same directory as the
# driver's shared library.
#TrustedCerts=

# AllowLargeResults(Optional): When set to 1, the driver allows for result sets in responses to be larger than 128 MB.
# AllowLargeResults=0

# UseDefaultLargeResultsDataset(Optional): The id of the dataset that you want to use to store temporary tables for large result sets.
# UseDefaultLargeResultsDataset=1

# LargeResultsDataSetId(Optional): DatasetId to store temporary tables created.
# This is a required setting if AllowLargeResults is set to 1.
# LargeResultsDataSetId=_bqodbc_temp_tables

# LargeResultsTempTableExpirationTime(Optional): Time in milliseconds before the temporary tables created expire.
# This is a required setting if AllowLargeResults is set to 1.
# LargeResultsTempTableExpirationTime=3600000

# AllowHtapiForLargeResults(Optional): Storage read API is used to fetch results when this is enabled.
# AllowHtapiForLargeResults=0
