# To use this INI file, replace <INSTALLDIR> with the
# directory the tarball was extracted to.

[ODBC Drivers]
ODBC Driver for BigQuery=Installed

[ODBC Driver for BigQuery]
Description=ODBC Driver for BigQuery
#Driver=<INSTALLDIR>/lib/libgoogle_cloud_odbc_bq_driver.so
#Driver=<INSTALLDIR>/lib/libgoogle_cloud_odbc_bq_driver.dylib # MacOS
