# To use this INI file, replace <INSTALLDIR> with the
# directory the tarball was extracted to.

[ODBC Drivers]
BigQuery ODBC Driver=Installed

[BigQuery ODBC Driver]
Description=BigQuery ODBC Driver
#Driver=<INSTALLDIR>/lib/libgoogle_cloud_odbc_bq_driver.so
#Driver=<INSTALLDIR>/lib/libgoogle_cloud_odbc_bq_driver.dylib # MacOS
