# To use this INI file, replace <INSTALLDIR> with the 
# directory the tarball was extracted to.

[ODBC Drivers]
Google ODBC Driver for Google BigQuery=Installed

[Google ODBC Driver for Google BigQuery]
Description=Google ODBC Driver for Google BigQuery
#Driver=<INSTALLDIR>/lib/libgoogle_cloud_odbc_bq_driver.so
#Driver=<INSTALLDIR>/lib/libgoogle_cloud_odbc_bq_driver.dylib # MacOS

