# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

licenses(["notice"])  # Apache v2

package(default_visibility = ["//visibility:private"])

# Define a config_setting for Windows
config_setting(
    name = "windows",
    constraint_values = ["@platforms//os:windows"],
)

# Library and tests for Driver internal
load(":google_cloud_odbc_bq_driver_internal.bzl", "google_cloud_odbc_bq_driver_internal_hdrs", "google_cloud_odbc_bq_driver_internal_srcs")

cc_library(
    name = "google_cloud_odbc_bq_driver_internal",
    srcs = google_cloud_odbc_bq_driver_internal_srcs + select({
        ":windows": [
            "bq_driver/internal/driver_adv_opt_form.cc",
            "bq_driver/internal/driver_form.cc",
            "bq_driver/internal/driver_form_proxy.cc",
            "bq_driver/internal/driver_log_form.cc",
        ],
        "//conditions:default": [],
    }),
    hdrs = google_cloud_odbc_bq_driver_internal_hdrs + select({
        ":windows": [
            "bq_driver/internal/driver_adv_opt_form.h",
            "bq_driver/internal/driver_form.h",
            "bq_driver/internal/driver_form_proxy.h",
            "bq_driver/internal/driver_log_form.h",
        ],
        "//conditions:default": [],
    }),
    copts = ["-std=c++17"],
    # TODO(sachinpro): remove this when we are able to compile arrow for bazel
    defines = ["NO_ARROW"],
    visibility = ["//:__pkg__"],
    deps = [
        "//google/cloud/odbc/bq_client_interface:odbc_bq_client_interface",
        "//google/cloud/odbc/internal:odbc_internal",
        "@com_google_absl//absl/base:core_headers",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:initialize",
        "@com_google_absl//absl/log:log_sink",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/time",
        "@com_google_absl//absl/time/internal/cctz:time_zone",
        "@com_google_cloud_cpp//:experimental-bigquery-rest",  # We need this dependency to use 'options' from client libraries
    ],
)

WINDOWS_ONLY_TESTS = ("bq_driver/internal/driver_form_test.cc", "bq_driver/internal/driver_log_form_test.cc", "bq_driver/internal/driver_form_proxy_test.cc", "bq_driver/internal/driver_adv_opt_form_test.cc")

cc_test(
    name = "driver_internal_utils_test",
    srcs = select({
        ":windows": glob(["bq_driver/internal/*_test.cc"]),
        "//conditions:default": glob(
            ["bq_driver/internal/*_test.cc"],
            exclude = WINDOWS_ONLY_TESTS,
        ),
    }),
    copts = ["-std=c++17"],
    tags = ["unit-tests"],
    deps = [
        "//google/cloud/odbc/testing:google_cloud_odbc_testing_bq_driver_utils",
        "//google/cloud/odbc/testing:google_cloud_odbc_testing_utils",
        "@com_google_googletest//:gtest_main",
    ],
)

# Library target for the Driver

load(":google_cloud_odbc_bq_driver.bzl", "google_cloud_odbc_bq_driver_hdrs", "google_cloud_odbc_bq_driver_srcs")

cc_library(
    name = "google_cloud_odbc_bq_driver",
    srcs = google_cloud_odbc_bq_driver_srcs,
    hdrs = google_cloud_odbc_bq_driver_hdrs,
    copts = ["-std=c++17"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//:google_cloud_odbc_bq_driver_internal",
    ],
)

WINDOWS_DRIVER_UTILS_TESTS = "bq_driver/odbc_windows_test.cc"

cc_test(
    name = "driver_utils_test",
    srcs = select({
        ":windows": glob(["bq_driver/*_test.cc"]),
        "//conditions:default": glob(
            ["bq_driver/*_test.cc"],
            exclude = [WINDOWS_DRIVER_UTILS_TESTS],
        ),
    }),
    tags = ["unit-tests"],
    deps = [
        "//google/cloud/odbc/testing:google_cloud_odbc_testing_bq_driver_utils",
        "//google/cloud/odbc/testing:google_cloud_odbc_testing_utils",
        "@com_google_googletest//:gtest_main",
    ],
)
