# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

licenses(["notice"])  # Apache v2

package(default_visibility = ["//visibility:private"])

# Library and tests for Driver internal
load(":google_cloud_odbc_bq_driver_internal.bzl", "google_cloud_odbc_bq_driver_internal_hdrs", "google_cloud_odbc_bq_driver_internal_srcs")

cc_library(
    name = "google_cloud_odbc_bq_driver_internal",
    srcs = google_cloud_odbc_bq_driver_internal_srcs,
    hdrs = google_cloud_odbc_bq_driver_internal_hdrs,
    visibility = ["//:__pkg__"],
    deps = [
        "//google/cloud/odbc/bq_client_interface:odbc_bq_client_interface",
        "//google/cloud/odbc/internal:odbc_internal",
        "@com_google_cloud_cpp//:experimental-bigquery-rest",  # We need this dependency to use 'options' from client libraries
    ],
)

[cc_test(
    name = driver_utils_test.replace("/", "_").replace(".cc", ""),
    timeout = "long",
    srcs = [driver_utils_test],
    tags = ["unit-tests"],
    deps = [
        "//:google_cloud_odbc_bq_driver_internal",
        "//google/cloud/odbc/testing:google_cloud_odbc_testing_utils",
        "@com_google_googletest//:gtest_main",
    ],
) for driver_utils_test in glob(["bq_driver/internal/*_test.cc"])]

# Library target for the Driver

load(":google_cloud_odbc_bq_driver.bzl", "google_cloud_odbc_bq_driver_hdrs", "google_cloud_odbc_bq_driver_srcs")

cc_library(
    name = "google_cloud_odbc_bq_driver",
    srcs = google_cloud_odbc_bq_driver_srcs,
    hdrs = google_cloud_odbc_bq_driver_hdrs,
    visibility = ["//:__subpackages__"],
    deps = [
        "//:google_cloud_odbc_bq_driver_internal",
    ],
)
