# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DO NOT EDIT -- GENERATED BY CMake -- Change the CMakeLists.txt file if needed

"""Automatically generated source lists for google_cloud_odbc_bq_driver - DO NOT EDIT."""

google_cloud_odbc_bq_driver_hdrs = [
    "bq_driver/odbc_commons.h",
    "bq_driver/odbc_connection.h",
    "bq_driver/odbc_descriptor.h",
    "bq_driver/odbc_diagnostics.h",
    "bq_driver/odbc_driver_metadata.h",
    "bq_driver/odbc_environment.h",
    "bq_driver/odbc_lock.h",
    "bq_driver/odbc_sql_requests.h",
    "bq_driver/odbc_sql_results.h",
    "bq_driver/odbc_statement.h",
    "bq_driver/odbc_trace.h",
    "bq_driver/odbc_utils.h",
]

google_cloud_odbc_bq_driver_srcs = [
    "bq_driver/odbc_api.cc",
    "bq_driver/odbc_commons.cc",
    "bq_driver/odbc_connection.cc",
    "bq_driver/odbc_descriptor.cc",
    "bq_driver/odbc_diagnostics.cc",
    "bq_driver/odbc_driver_metadata.cc",
    "bq_driver/odbc_environment.cc",
    "bq_driver/odbc_lock.cc",
    "bq_driver/odbc_sql_requests.cc",
    "bq_driver/odbc_sql_results.cc",
    "bq_driver/odbc_statement.cc",
    "bq_driver/odbc_trace.cc",
    "bq_driver/odbc_utils.cc",
]
