# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DO NOT EDIT -- GENERATED BY CMake -- Change the CMakeLists.txt file if needed

"""Automatically generated source lists for google_cloud_odbc_bq_driver_internal - DO NOT EDIT."""

google_cloud_odbc_bq_driver_internal_hdrs = [
    "bq_driver/internal/data_translation.h",
    "bq_driver/internal/diagnostics.h",
    "bq_driver/internal/odbc_conn_handle.h",
    "bq_driver/internal/odbc_env_handle.h",
    "bq_driver/internal/odbc_handle.h",
    "bq_driver/internal/odbc_query.h",
    "bq_driver/internal/odbc_sql_fns.h",
    "bq_driver/internal/odbc_sql_info.h",
    "bq_driver/internal/odbc_sql_type_info.h",
    "bq_driver/internal/odbc_statement_handle.h",
    "bq_driver/internal/trace_utils.h",
    "bq_driver/internal/utils.h",
]

google_cloud_odbc_bq_driver_internal_srcs = [
    "bq_driver/internal/data_translation.cc",
    "bq_driver/internal/diagnostics.cc",
    "bq_driver/internal/odbc_conn_handle.cc",
    "bq_driver/internal/odbc_env_handle.cc",
    "bq_driver/internal/odbc_handle.cc",
    "bq_driver/internal/odbc_query.cc",
    "bq_driver/internal/odbc_sql_fns.cc",
    "bq_driver/internal/odbc_sql_info.cc",
    "bq_driver/internal/odbc_sql_type_info.cc",
    "bq_driver/internal/odbc_statement_handle.cc",
    "bq_driver/internal/trace_utils.cc",
    "bq_driver/internal/utils.cc",
]
