# ~~~
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ~~~

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/03597a01ee50ed33e9dfd640b249b4be3799d395.zip"],
  strip_prefix = "googletest-03597a01ee50ed33e9dfd640b249b4be3799d395",
)

new_local_repository(
    name = "system_libs",
    path = "/lib/x86_64-linux-gnu/",
    build_file_content = """
cc_library(
    name = "odbc_driver_manager",
    srcs = ["libodbc.so"],
    visibility = ["//visibility:public"],
)
""",
)
