[Driver]
# LogLevel(Optional): abseil logging severity
# 0 = (OFF), 1 = (ERROR), 2 = (WARNING), 3 = (INFO)
LogLevel=0

# LogPath(Required if LogLevel > 0): Folder where log files are created.
# Inside the container, /tmp/google_logs is always writable.
LogPath=/tmp/google_logs

LogFileCount=50
LogFileSize=2000
MaxThreads=8
