[ODBC Data Sources]
ODBCTestsDSN=Google BigQuery ODBC Driver

[ODBCTestsDSN]
Description=Google BigQuery ODBC Driver
Driver=/usr/local/lib/libgoogle_cloud_odbc_bq_driver.so
Catalog=bigquery-devtools-drivers
DefaultDataset=ODBC_TEST_DATASET_SACHIN
OAuthMechanism=0
KeyFilePath=/usr/local/google/home/sachinpurohit/work/serviceAccountKeyProd.json
# TrustedCerts=/etc/ssl/certs/ca-certificates.crt
