[ODBC Data Sources]
ODBCTestsDSN=Google BigQuery ODBC Driver

[ODBCTestsDSN]
Description=Google BigQuery ODBC Driver

## 
# Driver=/usr/local/lib/libgoogle_cloud_odbc_bq_driver.so
Catalog=bigquery-devtools-drivers

## DefaultDataset is optional 
# DefaultDataset=ODBC_TEST_DATASET

# OAuth Mechanism(Required): The OAuth mechanism to use. There are three choices:
# 0 = Service or User Authentication
# 3 = Application Default Credentials
# 4 = External account Authentication
OAuthMechanism=3

## KeyFilePath is not needed for Application Default Credentials
# KeyFilePath=<path-to-the-key-json>

# TrustedCerts=/etc/ssl/certs/ca-certificates.crt
