// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "properties.h"

namespace google::cloud::odbc_tests {

std::map<SQLUSMALLINT, std::string const> const kAllOdbc3Functions = {
    //{SQL_API_SQLALLOCENV, "SQL_API_SQLALLOCENV"},
    {SQL_API_SQLALLOCHANDLE, "SQL_API_SQLALLOCHANDLE"},
    {SQL_API_SQLGETDESCFIELD, "SQL_API_SQLGETDESCFIELD"},
    {SQL_API_SQLBINDCOL, "SQL_API_SQLBINDCOL"},
    {SQL_API_SQLGETDESCREC, "SQL_API_SQLGETDESCREC"},
    {SQL_API_SQLCANCEL, "SQL_API_SQLCANCEL"},
    {SQL_API_SQLGETDIAGFIELD, "SQL_API_SQLGETDIAGFIELD"},
    {SQL_API_SQLCLOSECURSOR, "SQL_API_SQLCLOSECURSOR"},
    {SQL_API_SQLGETDIAGREC, "SQL_API_SQLGETDIAGREC"},
    {SQL_API_SQLCOLATTRIBUTE, "SQL_API_SQLCOLATTRIBUTE"},
    {SQL_API_SQLGETENVATTR, "SQL_API_SQLGETENVATTR"},
    {SQL_API_SQLCONNECT, "SQL_API_SQLCONNECT"},
    {SQL_API_SQLGETFUNCTIONS, "SQL_API_SQLGETFUNCTIONS"},
    {SQL_API_SQLCOPYDESC, "SQL_API_SQLCOPYDESC"},
    {SQL_API_SQLGETINFO, "SQL_API_SQLGETINFO"},
    {SQL_API_SQLDATASOURCES, "SQL_API_SQLDATASOURCES"},
    {SQL_API_SQLGETSTMTATTR, "SQL_API_SQLGETSTMTATTR"},
    {SQL_API_SQLDESCRIBECOL, "SQL_API_SQLDESCRIBECOL"},
    {SQL_API_SQLGETTYPEINFO, "SQL_API_SQLGETTYPEINFO"},
    {SQL_API_SQLDISCONNECT, "SQL_API_SQLDISCONNECT"},
    {SQL_API_SQLNUMRESULTCOLS, "SQL_API_SQLNUMRESULTCOLS"},
    {SQL_API_SQLDRIVERS, "SQL_API_SQLDRIVERS"},
    {SQL_API_SQLPARAMDATA, "SQL_API_SQLPARAMDATA"},
    {SQL_API_SQLENDTRAN, "SQL_API_SQLENDTRAN"},
    {SQL_API_SQLPREPARE, "SQL_API_SQLPREPARE"},
    {SQL_API_SQLEXECDIRECT, "SQL_API_SQLEXECDIRECT"},
    {SQL_API_SQLPUTDATA, "SQL_API_SQLPUTDATA"},
    {SQL_API_SQLEXECUTE, "SQL_API_SQLEXECUTE"},
    {SQL_API_SQLROWCOUNT, "SQL_API_SQLROWCOUNT"},
    {SQL_API_SQLFETCH, "SQL_API_SQLFETCH"},
    {SQL_API_SQLSETCONNECTATTR, "SQL_API_SQLSETCONNECTATTR"},
    {SQL_API_SQLFETCHSCROLL, "SQL_API_SQLFETCHSCROLL"},
    {SQL_API_SQLSETCURSORNAME, "SQL_API_SQLSETCURSORNAME"},
    {SQL_API_SQLFREEHANDLE, "SQL_API_SQLFREEHANDLE"},
    {SQL_API_SQLSETDESCFIELD, "SQL_API_SQLSETDESCFIELD"},
    {SQL_API_SQLFREESTMT, "SQL_API_SQLFREESTMT"},
    {SQL_API_SQLSETDESCREC, "SQL_API_SQLSETDESCREC"},
    {SQL_API_SQLGETCONNECTATTR, "SQL_API_SQLGETCONNECTATTR"},
    {SQL_API_SQLSETENVATTR, "SQL_API_SQLSETENVATTR"},
    {SQL_API_SQLGETCURSORNAME, "SQL_API_SQLGETCURSORNAME"},
    {SQL_API_SQLSETSTMTATTR, "SQL_API_SQLSETSTMTATTR"},
    {SQL_API_SQLGETDATA, "SQL_API_SQLGETDATA"},
    {SQL_API_SQLCOLUMNS, "SQL_API_SQLCOLUMNS"},
    {SQL_API_SQLSTATISTICS, "SQL_API_SQLSTATISTICS"},
    {SQL_API_SQLSPECIALCOLUMNS, "SQL_API_SQLSPECIALCOLUMNS"},
    {SQL_API_SQLTABLES, "SQL_API_SQLTABLES"},
    {SQL_API_SQLBINDPARAMETER, "SQL_API_SQLBINDPARAMETER"},
    {SQL_API_SQLNATIVESQL, "SQL_API_SQLNATIVESQL"},
    {SQL_API_SQLBROWSECONNECT, "SQL_API_SQLBROWSECONNECT"},
    {SQL_API_SQLNUMPARAMS, "SQL_API_SQLNUMPARAMS"},
    // {SQL_API_SQLBULKOPERATIONS, "SQL_API_SQLBULKOPERATIONS"},
    {SQL_API_SQLPRIMARYKEYS, "SQL_API_SQLPRIMARYKEYS"},
    {SQL_API_SQLCOLUMNPRIVILEGES, "SQL_API_SQLCOLUMNPRIVILEGES"},
    {SQL_API_SQLPROCEDURECOLUMNS, "SQL_API_SQLPROCEDURECOLUMNS"},
    {SQL_API_SQLDESCRIBEPARAM, "SQL_API_SQLDESCRIBEPARAM"},
    {SQL_API_SQLPROCEDURES, "SQL_API_SQLPROCEDURES"},
    {SQL_API_SQLDRIVERCONNECT, "SQL_API_SQLDRIVERCONNECT"},
    // {SQL_API_SQLSETPOS, "SQL_API_SQLSETPOS"},
    {SQL_API_SQLFOREIGNKEYS, "SQL_API_SQLFOREIGNKEYS"},
    {SQL_API_SQLTABLEPRIVILEGES, "SQL_API_SQLTABLEPRIVILEGES"},
    {SQL_API_SQLMORERESULTS, "SQL_API_SQLMORERESULTS"},
    //{SQL_API_SQLSETSCROLLOPTIONS, "SQL_API_SQLSETSCROLLOPTIONS"}
};

SQLRETURN GetAllFunctions(std::shared_ptr<ODBCHandles> conn) {
  SQLUSMALLINT supported_functions[450];
  auto status = SQLGetFunctions(conn->hdbc, SQL_API_ODBC3_ALL_FUNCTIONS,
                                supported_functions);
  if (status == SQL_SUCCESS) {
    for (auto function : kAllOdbc3Functions) {
      if (!SQL_FUNC_EXISTS(supported_functions, function.first)) {
        // TODO(#10): Remove printf and support logging
        printf("%s: NOT AVAILABLE\n", function.second.c_str());
        return SQL_ERROR;
      }
    }
  }
  return status;
}

}  // namespace google::cloud::odbc_tests
