# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(default_visibility = ["//:__subpackages__"])

licenses(["notice"])  # Apache 2.0

load(":odbc_internal.bzl", "odbc_internal_hdrs", "odbc_internal_srcs")

################################################################################
# Generate version.h from version.h.in
################################################################################
genrule(
    name = "generate_version_h",
    srcs = ["version.h.in"],
    outs = ["version.h"],
    cmd = """
      sed -e 's|@PROJECT_VERSION_MAJOR@|$(PROJECT_VERSION_MAJOR)|g' \
          -e 's|@PROJECT_VERSION_MINOR@|$(PROJECT_VERSION_MINOR)|g' \
          -e 's|@PROJECT_VERSION_PATCH@|$(PROJECT_VERSION_PATCH)|g' \
          -e 's|@PROJECT_VERSION@|$(PROJECT_VERSION)|g' \
          -e 's|@FULL_VERSION@|$(FULL_VERSION)|g' \
          $(SRCS) > $@
    """,
    visibility = ["//visibility:public"],
)

################################################################################
# ODBC internal library
################################################################################
cc_library(
    name = "odbc_internal",
    srcs = odbc_internal_srcs,
    hdrs = odbc_internal_hdrs + [":generate_version_h"],  # add generated header
    strip_include_prefix = ".",
    include_prefix = "google/cloud/odbc/internal",
    deps = [
        "@com_google_cloud_cpp//:experimental-bigquery-rest",
    ],
)
[cc_test(
    name = odbc_internal_test.replace("/", "_").replace(".cc", ""),
    srcs = [odbc_internal_test],
    tags = ["unit-tests"],
    deps = [
        "//:odbc_internal",
        "@com_google_googletest//:gtest_main",
    ],
) for odbc_internal_test in glob(["*_test.cc"])]
