filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: cpp-bigquery-odbc
  owner: googleapis
  push:
    branch: ^main$
name: demo-sles-15-ci
substitutions:
  _BUILD_NAME: demo-install
  _DEPENDENCIES: 'iODBC'
  _DISTRO: demo-sles-15
  _TRIGGER_TYPE: ci
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
tags:
- ci
