filename: ci/cloudbuild/cloudbuild.yaml
name: integration-tests-scheduled
sourceToBuild:
  ref: refs/heads/main
  repoType: GITHUB
  uri: https://github.com/googleapis/cpp-bigquery-odbc
substitutions:
  _BUILD_NAME: integration-tests
  _DISTRO: ubuntu-22.04-install
  _DEPENDENCIES: 'BAZEL'
  _TRIGGER_TYPE: scheduled
tags:
- scheduled
