filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: cpp-bigquery-odbc
  owner: googleapis
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: integration-bq-driver-pr
substitutions:
  _BUILD_NAME: integration-bq-driver
  _DISTRO: ubuntu-22.04-install
  _TRIGGER_TYPE: pr
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
tags:
- pr
