filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: cpp-bigquery-odbc
  owner: googleapis
  pullRequest:
    branch: ^sachin-main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: msan-pr
substitutions:
  _BUILD_NAME: msan
  _DISTRO: ubuntu-msan
  _TRIGGER_TYPE: pr
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
tags:
- pr
