// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "google/cloud/odbc/bq_driver/internal/odbc_sql_fns.h"
#include "google/cloud/odbc/testing/utils/status_matchers.h"
#include <gtest/gtest.h>

namespace google::cloud::odbc_bq_driver_internal {

using ::google::cloud::odbc_internal::SQLStates;
using ::google::cloud::odbc_internal::StatusRecord;

TEST(PopulateSupportedODBC3Functions, AllODBC3SupportedFunctions) {
  SQLUSMALLINT odbc3_fns[SQL_API_ODBC3_ALL_FUNCTIONS_SIZE];
  StatusRecord status_record = PopulateSupportedODBC3Functions(odbc3_fns);
  EXPECT_TRUE(status_record.ok());

  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLALLOCHANDLE));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETDESCFIELD));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLSETCONNECTATTR));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLDRIVERS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLBINDCOL));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETDESCREC));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLCANCEL));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETDIAGFIELD));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLCLOSECURSOR));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETDIAGREC));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLCOLATTRIBUTE));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETENVATTR));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLCONNECT));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETFUNCTIONS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLCOPYDESC));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETINFO));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLDATASOURCES));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETSTMTATTR));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLDESCRIBECOL));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETTYPEINFO));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLDISCONNECT));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLNUMRESULTCOLS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLPARAMDATA));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLENDTRAN));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLPREPARE));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLEXECDIRECT));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLPUTDATA));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLEXECUTE));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLROWCOUNT));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLFETCH));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLFETCHSCROLL));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLSETCURSORNAME));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLFREEHANDLE));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLSETDESCFIELD));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLSETDESCREC));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETCONNECTATTR));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLSETENVATTR));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETCURSORNAME));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLSETSTMTATTR));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLGETDATA));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLCOLUMNS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLSTATISTICS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLSPECIALCOLUMNS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLTABLES));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLBINDPARAM));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLNATIVESQL));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLBROWSECONNECT));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLNUMPARAMS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLPRIMARYKEYS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLCOLUMNPRIVILEGES));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLPROCEDURECOLUMNS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLDESCRIBEPARAM));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLPROCEDURES));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLDRIVERCONNECT));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLFOREIGNKEYS));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLTABLEPRIVILEGES));
  EXPECT_EQ(SQL_TRUE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLMORERESULTS));
}

TEST(PopulateSupportedODBC3Functions, AllUnSupportedODBC3Functions) {
  SQLUSMALLINT odbc3_fns[SQL_API_ODBC3_ALL_FUNCTIONS_SIZE];
  StatusRecord status_record = PopulateSupportedODBC3Functions(odbc3_fns);
  EXPECT_TRUE(status_record.ok());

  EXPECT_EQ(SQL_FALSE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLBULKOPERATIONS));
  EXPECT_EQ(SQL_FALSE, SQL_FUNC_EXISTS(odbc3_fns, SQL_API_SQLSETPOS));
}

TEST(PopulateSupportedODBC2Functions, AllUnSupportedODBC2Functions) {
  SQLUSMALLINT odbc2_fns[kSqlApiAllFuncsSize];
  StatusRecord status_record = PopulateSupportedODBC2Functions(odbc2_fns);
  EXPECT_TRUE(status_record.ok());

  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLERROR]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLPARAMOPTIONS]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLSETSCROLLOPTIONS]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLSETPARAM]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLALLOCCONNECT]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLALLOCENV]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLALLOCSTMT]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLFREECONNECT]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLFREEENV]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLGETCONNECTOPTION]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLGETSTMTOPTION]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLSETCONNECTOPTION]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLSETSTMTOPTION]);
  EXPECT_EQ(SQL_FALSE, odbc2_fns[SQL_API_SQLTRANSACT]);
}

TEST(PopulateSupportedODBC3Functions, SupportedFunctionPointerNull) {
  StatusRecord status_record = PopulateSupportedODBC3Functions(nullptr);

  EXPECT_EQ(status_record.sql_state, SQLStates::k_HY024());
  EXPECT_EQ(status_record.message, "Argument supportedFunction cannot be null");
}

TEST(PopulateSupportedODBC2Functions, SupportedFunctionPointerNull) {
  StatusRecord status_record = PopulateSupportedODBC2Functions(nullptr);

  EXPECT_EQ(status_record.sql_state, SQLStates::k_HY024());
  EXPECT_EQ(status_record.message, "Argument supportedFunction cannot be null");
}

TEST(CheckFuncs, CheckODBC2True) {
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLERROR));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLPARAMOPTIONS));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLSETSCROLLOPTIONS));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLSETPARAM));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLALLOCCONNECT));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLALLOCENV));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLALLOCSTMT));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLFREECONNECT));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLFREEENV));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLFREESTMT));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLBINDPARAMETER));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLGETCONNECTOPTION));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLGETSTMTOPTION));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLSETCONNECTOPTION));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLSETSTMTOPTION));
  EXPECT_TRUE(IsFunctionIdOdbc2(SQL_API_SQLTRANSACT));
}

TEST(CheckFuncs, CheckODBC3True) {
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLALLOCHANDLE));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETDESCFIELD));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLSETCONNECTATTR));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLDRIVERS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLBINDCOL));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETDESCREC));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLCANCEL));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETDIAGFIELD));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLCLOSECURSOR));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETDIAGREC));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLCOLATTRIBUTE));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETENVATTR));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLCONNECT));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETFUNCTIONS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLCOPYDESC));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETINFO));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLDATASOURCES));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETSTMTATTR));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLDESCRIBECOL));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETTYPEINFO));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLDISCONNECT));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLNUMRESULTCOLS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLPARAMDATA));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLENDTRAN));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLPREPARE));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLEXECDIRECT));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLPUTDATA));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLEXECUTE));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLROWCOUNT));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLFETCH));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLFETCHSCROLL));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLSETCURSORNAME));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLFREEHANDLE));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLSETDESCFIELD));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLSETDESCREC));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETCONNECTATTR));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLSETENVATTR));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETCURSORNAME));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLSETSTMTATTR));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLGETDATA));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLCOLUMNS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLSTATISTICS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLSPECIALCOLUMNS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLTABLES));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLBINDPARAM));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLNATIVESQL));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLBROWSECONNECT));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLNUMPARAMS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLPRIMARYKEYS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLCOLUMNPRIVILEGES));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLPROCEDURECOLUMNS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLDESCRIBEPARAM));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLPROCEDURES));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLDRIVERCONNECT));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLFOREIGNKEYS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLTABLEPRIVILEGES));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLMORERESULTS));
  EXPECT_TRUE(IsFunctionIdOdbc3(SQL_API_SQLPROCEDURES));
}

TEST(CheckFuncs, CheckODBC2False) {
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLALLOCHANDLE));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETDESCFIELD));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLSETCONNECTATTR));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLDRIVERS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLBINDCOL));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETDESCREC));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLCANCEL));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETDIAGFIELD));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLCLOSECURSOR));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETDIAGREC));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLCOLATTRIBUTE));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETENVATTR));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLCONNECT));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETFUNCTIONS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLCOPYDESC));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETINFO));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLDATASOURCES));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETSTMTATTR));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLDESCRIBECOL));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETTYPEINFO));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLDISCONNECT));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLNUMRESULTCOLS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLPARAMDATA));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLENDTRAN));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLPREPARE));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLEXECDIRECT));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLPUTDATA));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLEXECUTE));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLROWCOUNT));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLFETCH));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLFETCHSCROLL));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLSETCURSORNAME));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLFREEHANDLE));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLSETDESCFIELD));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLSETDESCREC));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETCONNECTATTR));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLSETENVATTR));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETCURSORNAME));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLSETSTMTATTR));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLGETDATA));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLCOLUMNS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLSTATISTICS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLSPECIALCOLUMNS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLTABLES));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLNATIVESQL));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLBROWSECONNECT));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLNUMPARAMS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLPRIMARYKEYS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLCOLUMNPRIVILEGES));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLPROCEDURECOLUMNS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLDESCRIBEPARAM));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLPROCEDURES));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLDRIVERCONNECT));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLFOREIGNKEYS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLTABLEPRIVILEGES));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLMORERESULTS));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLBINDPARAM));
  EXPECT_FALSE(IsFunctionIdOdbc2(SQL_API_SQLPROCEDURES));
}

TEST(CheckFuncs, CheckODBC3False) {
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLERROR));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLPARAMOPTIONS));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLSETSCROLLOPTIONS));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLSETPARAM));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLALLOCCONNECT));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLALLOCENV));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLALLOCSTMT));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLFREECONNECT));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLFREEENV));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLGETCONNECTOPTION));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLGETSTMTOPTION));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLSETCONNECTOPTION));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLSETSTMTOPTION));
  EXPECT_FALSE(IsFunctionIdOdbc3(SQL_API_SQLTRANSACT));
}

}  // namespace google::cloud::odbc_bq_driver_internal
