# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DO NOT EDIT -- GENERATED BY CMake -- Change the CMakeLists.txt file if needed

"""Automatically generated source lists for odbc_bq_client_interface - DO NOT EDIT."""

odbc_bq_client_interface_hdrs = [
    "jobs.h",
    "datasets.h",
    "projects.h",
    "odbc_authentication.h",
    "odbc_bq_client.h",
    "setenv.h",
    "tables.h",
]

odbc_bq_client_interface_srcs = [
    "jobs.cc",
    "datasets.cc",
    "projects.cc",
    "odbc_authentication.cc",
    "odbc_bq_client.cc",
    "setenv.cc",
    "tables.cc",
]
