name: macOS-CMake-Builds

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        description: "The ref we want to compile"
        type: string

permissions:
  contents: read

jobs:
  cmake:
    name: cmake + ${{ matrix.os }} + ${{ matrix.shard }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: 'read'
      id-token: 'none'
    strategy:
      # Continue other builds even if one fails
      fail-fast: false
      matrix:
        os: [ macos-14, macos-15 ]
        shard: [ BqDriver ]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.checkout-ref }}
    - uses: google-github-actions/auth@v2
      with:
        create_credentials_file: true
        credentials_json: ${{ secrets.BUILD_CACHE_KEY }}
    - uses: actions/setup-python@v5
      id: py311
      with:
        python-version: '3.11'
    - uses: google-github-actions/setup-gcloud@v2
      with:
        version: '500.0.0'
      env:
        CLOUDSDK_PYTHON: ${{ steps.py311.outputs.python-path }}
    - name: Dynamic Configuration
      id: dynamic
      shell: bash
      run: |
        echo "vcpkg-version=$(cat ci/etc/vcpkg-version.txt)" >> "${GITHUB_OUTPUT}"
        echo "VCPKG_BINARY_SOURCES=clear;files,${{ runner.temp }}/vcpkg-cache,readwrite" >> "${GITHUB_ENV}"
    - name: Install bash >= 5.x and Ninja
      run: brew install bash ninja
    - name: Download cmake formula(3.29.0) and installl
      run: |
        brew unlink cmake
        curl -L https://github.com/Kitware/CMake/releases/download/v3.29.0/cmake-3.29.0-macos-universal.tar.gz -o cmake.tar.gz
        tar -xzf cmake.tar.gz
        sudo cp -r cmake-3.29.0-macos-universal/CMake.app/Contents/bin/* /usr/local/bin/
        sudo cp -r cmake-3.29.0-macos-universal/CMake.app/Contents/share/cmake-3.29 /usr/local/share/
        cmake --version
    - name: cmake version
      run: cmake --version
    - name: Download and Install sccache
      working-directory: "${{runner.temp}}"
      run: |
        curl -fsSL https://github.com/mozilla/sccache/releases/download/v0.9.1/sccache-v0.9.1-x86_64-apple-darwin.tar.gz | \
          tar -zxf - --strip-components=1 && \
        chmod +x sccache && \
        mv sccache /Users/runner/.cargo/bin/sccache
    - name: Install bison flex for 'arrow'
      run: brew install bison flex
    - name: Download and Install vcpkg
      working-directory: "${{runner.temp}}"
      run: |
        git clone --branch ${{ steps.dynamic.outputs.vcpkg-version }} https://github.com/microsoft/vcpkg.git
        vcpkg/bootstrap-vcpkg.sh -disableMetrics
    - name: Install iODBC
      run: |
        brew install libiodbc
    - name: Restore vcpkg binaries cache
      uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.temp }}/vcpkg-cache
        key: vcpkg-cache-${{ matrix.os }}-${{ matrix.shard }}-${{ hashFiles('vcpkg.json', 'ci/etc/vcpkg-version.txt') }}
        restore-keys: |
          vcpkg-cache-${{ matrix.os }}-${{ matrix.shard }}-
    - name: Setup the driver
      run: |
        export VCPKG_ROOT="${{ runner.temp }}/vcpkg"
        export PATH="$VCPKG_ROOT:/opt/homebrew/bin:$PATH"
        export LDFLAGS="-L$(brew --prefix libiodbc)/lib -liconv"
        export PATH="$(dirname ${{ steps.py311.outputs.python-path }}):$PATH"
        export CLOUDSDK_PYTHON="${{ steps.py311.outputs.python-path }}"
        bash ci/dependencies/driver-manager-setup-osx.sh
    - name: Save vcpkg binaries cache
      uses: actions/cache/save@v4
      if: always() && steps.cache-restore.outputs.cache-hit != 'true'
      with:
        path: ${{ runner.temp }}/vcpkg-cache
        key: vcpkg-cache-${{ matrix.os }}-${{ matrix.shard }}-${{ hashFiles('vcpkg.json', 'ci/etc/vcpkg-version.txt') }}
    - name: Build cpp-bigquery-odbc
      run: |
        export ODBC_PREFIX="$(brew --prefix libiodbc)"
        export ODBC_INCLUDE_PATH="$ODBC_PREFIX/include"
        export VCPKG_ROOT="${{ runner.temp }}/vcpkg"

        export PATH="$(dirname ${{ steps.py311.outputs.python-path }}):$(brew --prefix)/bin:/opt/homebrew/bin:$VCPKG_ROOT:$PATH"
        export CLOUDSDK_PYTHON="${{ steps.py311.outputs.python-path }}"
        export LDFLAGS="-L$(brew --prefix libiodbc)/lib -liconv"
        bash ci/gha/builds/macos-cmake.sh
    env:
      USE_BAZEL_VERSION: 7.0.0
      MATRIX_OS: ${{ matrix.os }}
      BAZEL_REMOTE_CACHE: https://storage.googleapis.com/gha-cache-cpp-bigquery-odbc/bazel-cache/${{ matrix.os }}
      SCCACHE_GCS_BUCKET: gha-cache-cpp-bigquery-odbc
      SCCACHE_GCS_KEY_PREFIX: sccache/${{ matrix.os }}
      SCCACHE_GCS_RW_MODE: READ_WRITE
      SCCACHE_IGNORE_SERVER_IO_ERROR: 1
