name: macOS-CMake-Builds

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        description: "The ref we want to compile"
        type: string

permissions:
  contents: read

jobs:
  cmake:
    name: cmake + ${{ matrix.os }} + ${{ matrix.shard }}
    runs-on: ${{ matrix.os }}-xl
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      # Continue other builds even if one fails
      fail-fast: false
      matrix:
        os: [ macos-13, macos-12 ]
        shard: [ Core ]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.checkout-ref }}
    - id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/676884463303/locations/global/workloadIdentityPools/odbc-gha/providers/github'
        service_account: 'bq-devtools-simba-drivers-test@bigquery-devtools-drivers.iam.gserviceaccount.com'
    - uses: google-github-actions/setup-gcloud@v1
    - name: Dynamic Configuration
      id: dynamic
      shell: bash
      run: |
        echo "vcpkg-version=$(cat ci/etc/vcpkg-version.txt)" >> "${GITHUB_OUTPUT}"
    - name: Install bash >= 5.x and Ninja
      run: brew install bash ninja
    - name: Download and Install sccache
      working-directory: "${{runner.temp}}"
      run: |
        curl -fsSL https://github.com/mozilla/sccache/releases/download/v0.5.4/sccache-v0.5.4-x86_64-apple-darwin.tar.gz | \
          tar -zxf - --strip-components=1 && \
        chmod +x sccache && \
        mv sccache /Users/runner/.cargo/bin/sccache
    - name: Download and Install vcpkg
      working-directory: "${{runner.temp}}"
      run: |
        mkdir -p vcpkg
        curl -fsSL "https://github.com/microsoft/vcpkg/archive/${{ steps.dynamic.outputs.vcpkg-version }}.tar.gz" |
            tar -C vcpkg --strip-components=1 -zxf -
        vcpkg/bootstrap-vcpkg.sh -disableMetrics
    - name: Build cpp-bigquery-odbc
      run: |
        export VCPKG_ROOT="${{ runner.temp }}/vcpkg"
        /usr/local/bin/bash ci/gha/builds/macos-cmake.sh
    env:
      USE_BAZEL_VERSION: 6.2.1
      BAZEL_REMOTE_CACHE: https://storage.googleapis.com/cpp-bigquery-odbc-gha-cache/bazel-cache/${{ matrix.os }}
      SCCACHE_GCS_BUCKET: cpp-bigquery-odbc-gha-cache
      SCCACHE_GCS_KEY_PREFIX: sccache/${{ matrix.os }}
      SCCACHE_GCS_RW_MODE: READ_WRITE
      SCCACHE_IGNORE_SERVER_IO_ERROR: 1
      VCPKG_BINARY_SOURCES: x-gcs,gs://cpp-bigquery-odbc-gha-cache/vcpkg-cache/${{ matrix.os }},readwrite
