name: "gha: macOS & Windows"

on:
  # Only trigger on actual pushes to these branches.
  # A PR merge counts as a push to the target branch.
  push:
    branches: [ 'main', 'ci-gha**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-flight:
    environment: >-
      ${{
          (github.event_name == 'push' && 'internal') ||
          (contains(fromJSON(vars.TRUSTED_FORKS), github.actor) && 'internal') ||
          'external'
      }}
    name: Require Approval for External PRs
    runs-on: ubuntu-latest
    outputs:
      checkout-sha: ${{ steps.save-sha.outputs.sha }}
    steps:
      - name: Save SHA
        id: save-sha
        run: echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT

  # Run other jobs once the `pre-flight` job passes. When the `pre-flight`
  # job requires approval, these blocks all the other jobs. The jobs are defined
  # in separate files to keep the size of this file under control. Note how
  # the additional jobs inherit any secrets needed to use the remote caches and
  # receive what version to checkout as an input.
  macos-cmake:
    name: macOS-CMake
    needs: [pre-flight]
    uses: ./.github/workflows/macos-cmake.yml
    with:
      checkout-ref: ${{ needs.pre-flight.outputs.checkout-sha }}
    secrets: inherit
  windows-cmake:
    name: Windows-CMake
    needs: [pre-flight]
    uses: ./.github/workflows/windows-cmake.yml
    with:
      checkout-ref: ${{ needs.pre-flight.outputs.checkout-sha }}
    secrets: inherit
