name: Windows-Builds

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        description: "The ref we want to compile"
        type: string

permissions:
  contents: read

jobs:
  cmake:
    name: cmake + ${{ matrix.msvc }} + ${{ matrix.arch }} + ${{ matrix.shard }}
    runs-on:
      group: cpp-runners
      labels: ${{ endsWith(matrix.msvc, '-2019') && 'windows-2019' || 'windows-2022' }}
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      # Continue other builds even if one fails
      fail-fast: false
      matrix:
        msvc: [ msvc-2022, msvc-2019 ]
        # TODO(b/357810060): Add x86 arch
        arch: [ x64, x86 ]
        shard: [ Core, BqDriver ]
        exclude:
          - msvc: msvc-2019
            shard: Core
    env:
      DRIVER_ARCH: ${{ matrix.arch }}
      BUILD_SHARD: ${{ matrix.shard }}
      SCCACHE_GCS_BUCKET: gha-cache-cpp-bigquery-odbc
      SCCACHE_GCS_KEY_PREFIX: sccache/${{ matrix.msvc }}/${{ matrix.arch}}
      SCCACHE_GCS_RW_MODE: READ_WRITE
      SCCACHE_IGNORE_SERVER_IO_ERROR: 1
      VCPKG_BINARY_SOURCES: x-gcs,gs://gha-cache-cpp-bigquery-odbc/vcpkg-cache/${{ matrix.msvc }},readwrite
      VCPKG_TRIPLET: ${{ matrix.arch }}-windows
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.checkout-ref }}
    - uses: google-github-actions/auth@v2
      with:
        create_credentials_file: true
        credentials_json: ${{ secrets.BUILD_CACHE_KEY }}
    - uses: actions/setup-python@v5
      id: py311
      with:
        python-version: '3.11'
    - uses: google-github-actions/setup-gcloud@v2
      env:
        CLOUDSDK_PYTHON: ${{ steps.py311.outputs.python-path }}
    - name: Download and Install ODBC Driver
      shell: powershell
      # TODO(b/357810060): Enable msvc-2019 arch
      if: matrix.msvc == 'msvc-2022' && matrix.shard == 'Core'
      run: |
        .\ci\gha\builds\lib\odbc-driver-install.ps1
    - name: Run DSN Creation Script
      shell: powershell
      run: |
        Write-Output "Downloading service account key from Secret Manager..."
        gcloud secrets versions access latest --secret=service-account-auth-keys --out-file="service_account_auth_keys.json"
        Write-Output "Downloaded service account key"

        $arch = if ($env:DRIVER_ARCH -eq 'x64') { '64' } else { '32' }
        $regFilePath = Join-Path $PWD.Path "ci\gha\builds\lib\system_dsn_setup_$arch.reg"
        Write-Output "Running DSN creation script from $regFilePath ..."
        reg import $regFilePath
        Write-Output "DSN creation completed."
    - name: Dynamic Configuration
      id: dynamic
      shell: bash
      run: |
        echo "vcpkg-version=$(cat ci/etc/vcpkg-version.txt)" >> "${GITHUB_OUTPUT}"
    - name: Download and Install sccache
      working-directory: "${{runner.temp}}"
      shell: bash
      run: |
        curl -fsSL https://github.com/mozilla/sccache/releases/download/v0.5.4/sccache-v0.5.4-x86_64-pc-windows-msvc.tar.gz | \
          tar -zxf - --strip-components=1
        chmod +x sccache.exe
        mv sccache.exe /c/Users/runneradmin/.cargo/bin
    - name: Download and Install vcpkg
      shell: bash
      run: |
        cd "${TEMP}"
        mkdir .build
        cd .build
        git clone --branch ${{ steps.dynamic.outputs.vcpkg-version }} https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
    # go/github-actions#gha-bestpractices explains why we use a SHA instead of
    # a named version for this runner. We could avoid using this runner with the
    # ideas from:
    #   https://github.com/microsoft/vswhere/wiki/Find-VC
    # Note that in other runners the publisher is GitHub. If we trust GitHub
    # to run the VM, we should trust their runners.
    - uses: ilammy/msvc-dev-cmd@cec98b9d092141f74527d0afa6feb2af698cfe89 # @v1.21.1
      with:
        arch: ${{ matrix.arch }}
    - name: Build cpp-bigquery-odbc
      shell: bash
      run: |
        export VCPKG_ROOT="${TEMP}/.build/vcpkg"
        export CLOUDSDK_PYTHON="${{ steps.py311.outputs.python-path }}"
        # Put the CMake output in a directory with more space and keep it short
        # to avoid running into the MSVC limits.
        export CMAKE_OUT='c:\b'
        export MSVC_VERSION="${{ matrix.msvc }}"
        export BRANCH_IDENTIFIER=$(echo "${{ github.ref_name }}" | tr '[:punct:]' '_')
        export CPP_BIGQUERY_ODBC_TEST_TABLE_PREFIX="windows_${BRANCH_IDENTIFIER}_${MSVC_VERSION//[-:;.,?\/]/_}_${{ matrix.arch}}_$BUILD_SHARD"
        export CPP_BIGQUERY_ODBC_TEST_SERVICE_ACCOUNT_AUTH_KEY="C:\\a\\cpp-bigquery-odbc\\cpp-bigquery-odbc\\service_account_auth_keys.json"
        if [ "${{ matrix.msvc }}" == "msvc-2022" ]; then
          ci/gha/builds/windows-cmake-integration.sh
        else
          ci/gha/builds/windows-cmake.sh
        fi
